version: '4'
services:
  nginx:
    image: nginx_test
    build:
      context: .
      dockerfile: build/nginx.dockerfile
    volumes:
      - ./nginx/etc/nginx:/etc/nginx
      - ./nginx/var/www:/var/www
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 172.16.1.2
  server:
    image: web
    build:
      context: .
      dockerfile: build/web.dockerfile
    networks:
      default:
        ipv4_address: 172.16.1.5
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24