version: '4'
services:
  nginx:
    image: nginx_test
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./etc/nginx:/etc/nginx
      - ./var/www:/var/www
    ports:
      - "80:80"
